# Basic
title: 王凯男
subtitle: Charles Wong
description:
# 头像里面的标题
avatarTitle: goodfelling
# 头像里面的描述
avatarDesc: 编程·管理·读书
url: "http://wkn.github.io"

# Comment
comment:
    disqus: wkn456
    # duoshuo: freeWind

# Social
social:
    weibo:
    github: blackface123
    # twitter: 
    mail: wkn1714178948@163.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id:

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id:
    host: auto


permalink: /:year/:month/:title/
# Format
markdown: kramdown
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear #背景Mask

# The blog button should not be removed.
blog_button:
    title: 主页

# Navigation buttons in the front page.s
nav:
    - {title: 存档, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于, description: about, url: '/about'}      
    

# Pagination
plugins: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


